config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'static_pages/sign_in'
  get 'sign_up', to: 'users#new'
  post 'sign_up', to: 'users#create'

  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: {minimum:3, maximum:100}

  before_save {self.email = email.downcase}
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, presence: true, length: {maximum: 255}, format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}

  has_secure_password
  validates :password, presence:true, length: {minimum: 6}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def sign_up
  end

  def sign_in
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      render html:"Add user" + user_params["name"]
    else
      render 'new'
    end
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Xtower</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger sign_error">
      <%= @user.errors.full_messages.first %>
    </div>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <body>
    <div class="background">
      <div class="container">
        <div class="centerarea">
          <h1 class="home-logo">XTower</h1>
          <h1 class="solgan">团队协作本来就应该这么简单</h1>
          <p><button class="btn btn-primary">免费注册</button></p>
          <p><button class="btn btn-link">登录</button></p>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/users/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
</head>
<body>
  <div class="background-color">
    <div class="container">
      <div class="sign-up-area">
        <h1 class="logo">Tower</h1>
        <div class="sign-box">
          <h3 class="sign-title">注册</h3>
          <%= form_for(@user, url: sign_up_path) do |f| %>
            <%= render 'shared/error_messages' %>
            <p><input class="form-control" placeholder="团队名称"></p>
            <p><%= f.text_field :name, class: "form-control", placeholder: "你的名字" %></p>
            <p><%= f.email_field :email, class: "form-control", placeholder: "邮箱,例如: qq号码@qq.com" %></p>
            <p><%= f.password_field :password, class: "form-control", placeholder: "密码， 至少包含6位字符" %></p>
            <p><%= f.submit "注册", class: "btn btn-primary sign-button" %></p>
            <p><button class="btn btn-link sign-link">已有账号？直接登录</button></p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</body>
</html>

app/views/users/sign_in.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
  </head>
  <body>
    <div class="background-color">
      <div class="container">
        <div class="sign-in-area">
          <h1 class="logo">Tower</h1>
          <div class="sign-box">
            <h3 class="sign-title">登录</h3>
            <p>
              <input type="email" class="form-control" placeholder="登录邮箱" />
            </p>
            <p>
              <input type="password" class="form-control" placeholder="密码" />
            </p>
            <div class="form-check">
              <label class="checkbox-inline">
                <input type="checkbox" class="form-check-input">
                <span class="form-check-label">下次自动登录</span>
              </label>
              <button class="btn btn-link sign-link forget-button">忘记密码了？</button>
            </div>
            <p><button class="btn btn-primary">登录</button></p>
            <p>
              <button class="btn btn-link sign-link">
                没有账号？立即注册
              </button>
            </p>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>